#!/usr/bin/env bash

# End script if one of the lines fails
set -e

# Get the current directory (scripts/)
ROOT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
# Traverse up to get to the root directory
ROOT_DIR="$(dirname "$ROOT_DIR")"

SCRIPTS_DIR=scripts
IOS_SUBMODULE_DIR=ext/ios

RED='\033[0;31m' # Red color
GREEN='\033[0;32m' # Green color
NC='\033[0m' # No Color

echo -e "${GREEN}[*] START ${NC}"

echo -e "${GREEN}[*] Building framework ${NC}"
cd ${ROOT_DIR}/${IOS_SUBMODULE_DIR}
./build.sh

echo -e "${GREEN}[*] DONE ${NC}"
